### ISSUE TITLE
Generate a BitmapFont from a TTF file

### ISSUE THREAD

**Issue by Kernald** [korlibs/korim#16]
What would be the proper way to load a TTF file? As far as I understand, the current implementation of `BitmapFontGenerator` relies on the font being installed on the system - which might not be the case. I guess we can assume that it's possible to get a `VfsFile` pointing to a TTF file - it should be possible from there to generate a bitmap font.

**Comment by soywiz** [comment]
Not directly possible, but I have plans to implement this soon. As well as allowing to draw text from TTF without the need of creating a BitmapFont first.

**Comment by soywiz** [comment]
Fixed by #22
