### ISSUE TITLE
BitmapFont.drawText doesn't respect the colour

### ISSUE THREAD

**Issue by Kernald** [korlibs/korim#17]
`drawText` has a `color` parameter, but it isn't used. The text is always drawn in white.

https://github.com/korlibs/korim/blob/107f3f2c64a9c75aa014ffcf9d88a1ccadb82c09/korim/src/commonMain/kotlin/com/soywiz/korim/font/BitmapFont.kt#L35-L49

**Comment by soywiz** [comment]
Fixed by #22
