### ISSUE TITLE
Reading quantization tables of JPEG file on Android

### ISSUE THREAD

**Issue by BioGeek** [korlibs/korim#56]
I'm trying to read the quantization tables of a JPEG file on Android. 
It seems that [JPEGDecoder](https://github.com/korlibs/korim/blob/master/old/korim-jpeg/src/commonMain/kotlin/com/soywiz/korim/format/jpg/JPEGDecoder.kt)  reads the  quantization tables. 

But I'm still a beginner with Kotlin so I haven't yet figured out how I go from a string with the path to the JPEG file to printing out the quantization tables.

(Also [asked on Stackoverflow](https://stackoverflow.com/questions/62516038/reading-quantization-tables-of-jpeg-files-on-android))

Thanks in advance!

**Comment by soywiz** [comment]
Replied here: https://soywiz.slack.com/archives/C03B2H44G/p1592924847022800
