### ISSUE TITLE
Image flipping problem, exif rotation and flipping support

### ISSUE THREAD

**Issue by lemkoleg** [korlibs/korim#59]
There is an image whose width is less than height.
If I read the image and write it back, the image flips 90 °.

"
fun getImmage() {

        val fileName = resourcesVfs["SomeImage.jpg"]
        val image32 = fileName.readBitmap().toBMP32()
        val resfile = resourcesVfs["ResImage.jpg"]
        resfile.writeBytes(image32.encode(PNG))
    }
"
[11.zip](https://github.com/korlibs/korim/files/4893375/11.zip)

**Comment by soywiz** [comment]
https://github.com/recurser/exif-orientation-examples
