### ISSUE TITLE
I am getting "kotlin.NotImplementedError" in ImageFormat.kt

### ISSUE THREAD

**Issue by min2222** [korlibs/korim#65]
Hi I am trying to decompress a .imy file in a game called Criminal Girls and I found this script you made, but when I try to run this script I get "kotlin.NotImplementedError" in ImageFormat.kt How do I fix this?

script : https://github.com/talestra/talestrakt/blob/master/game-criminalgirls/src/com/talestra/criminalgirls/CriminalGirls.kt
error log : https://pastebin.com/NmL4adu2

**Comment by soywiz** [comment]
This is probably unrelated to KorIM. Since you have opened an issues there, I'm closing this one. I will probably split that repo into several repos one per project so each one can be in a specific working version for that project.
